export const BookData = [
    {
        id: 0,
        book_name: "The Haunting of Hill House",
        book_description: "The greatest haunted house story ever written, the inspiration for a 10-part Netflix series directed by Mike Flanagan and starring Michiel Huisman, Carla Gugino, and Timothy Hutton",
        book_url: "https://m.media-amazon.com/images/I/81mozNKlfbL._SL1500_.jpg",
        print_length: "208 pages",
        language: "English",
        author_name: "Shirley Jackson",
        price: "999.99",
    },
    {
        id: 1,
        book_name: "Ancient History of India",
        book_description: "Ancient History of India has been designed for aspirants of Civil Services and various State Services examinations. This book comprehensively covers the syllabus of the subject Ancient Indian History and Culture (for both Preliminary and Main exams). As per the demand of the syllabus, the book not only encompasses political, social, and economic history, but also sheds light on cultural aspects such as art forms, literature, and architecture of the ancient period. The chapters have been developed after extensive research and contain well-organized data, information, maps, and images under each topic. Previous years’ questions have been included in the book and practice questions in online resources.",
        book_url: "https://m.media-amazon.com/images/I/81f-yXdTAxL._SY425_.jpg",
        print_length: "280 pages",
        language: "English",
        author_name: "Snehil Tripathi Sonali Bansal",
        price: "335",
    },
    {
        id: 2,
        book_name: "Gain Your Financial Freedom with the 1% Formula",
        book_description: "Gain Your Financial Freedom also contains stories of people who used the 1% formula and created a nest egg without giving in to stress, anxiety or overwork. This book is a must-read for anyone who wants long-term wealth creation and a comfortable lifestyle off that wealth so that they don’t have to keep working for money.",
        book_url: "https://m.media-amazon.com/images/I/71sNJdxb-7L._SY425_.jpg",
        print_length: "200 pages",
        language: "English",
        author_name: "Deepak Mullick",
        price: "235",
    },
    {
        id: 3,
        book_name: "The Psychology of Money",
        book_description: "Timeless lessons on wealth, greed, and happiness doing well with money isn?t necessarily about what you know. It?s about how you behave. And behavior is hard to teach, even to really smart people. How to manage money, invest it, and make business decisions are typically considered to involve a lot of mathematical calculations, where data and formulae tell us exactly what to do. But in the real world, people don?t make financial decisions on a spreadsheet. They make them at the dinner table, or in a meeting room, where personal history, your unique view of the world, ego, pride, marketing, and odd incentives are scrambled together. In the psychology of money, the author shares 19 short stories exploring the strange ways people think about money and teaches you how to make better sense of one of life?s most important matters.",
        book_url: "https://m.media-amazon.com/images/I/41+tJ4avt6L._SY445_SX342_.jpg",
        print_length: "275 pages",
        language: "English",
        author_name: "Morgan Housel",
        price: "252",
    },
    {
        id: 4,
        book_name: "MY LIFE AN ILLUSTRATED AUTOBIOGRAPHY",
        book_description: "The story of my life has become intertwined with the story of this country. And somewhere along the way, as I met a million children across this land, I too learnt from a million minds. This book was not written to only tell my story. I want every young reader to think that this book is his or her story too.’ A.P.J. Abdul Kalam has been one of the most iconic figures of Independent India. A scientist, leader, thinker, teacher and writer, he achieved remarkable success in various fields. Yet, what endeared him to so many was his dedication to the idea of a developed India, his simple and direct way of interacting with people and his deep love for his fellowmen. In My Life, Kalam writes his life story starting from his days growing up at Rameswaram; about working on India’s space and missile programmes; his years as the eleventh President of India; and about his life thereafter. Full of anecdotes that demonstrate the importance of hard work, commitment, courage and innovative thinking, this autobiography is a wonderful introduction to a remarkable life. Beautifully illustrated and simply written. My Life will inspire readers of all ages.",
        book_url: "https://m.media-amazon.com/images/I/71iQ+vWirpL._SY425_.jpg",
        print_length: "119 pages",
        language: "English",
        author_name: "A P J Abdul Kalam",
        price: "169",
    },
    {
        id: 5,
        book_name: "Ratan Tata A Complete Biography",
        book_description: "An iconic Indian industrialist, Ratan Tata, has been a stalwart of the Indian business ecosystem. Born in Mumbai in the famed Tata family, he served as the chairman of Tata Sons and of the Tata Group (from 1990 to 2012, and 201617. Felicitated with the highest civilian awards of India, the Padma Vibhushan (2008) and Padma Bhushan (2000), Tata has been a philanthropist and an active investor in the Indian startup community. He was instrumental in many of the pivotal acquisitions (Tetley, Jaguar Land Rover, Corus, Air India) that ushered an era of modernity and competitiveness in this revered business group.",
        book_url: "https://m.media-amazon.com/images/I/41hP-NHD5nL._SX342_SY445_.jpg",
        print_length: "168 pages",
        language: "English",
        author_name: "A.K. Gandhi ",
        price: "174",
    },
    {
        id: 6,
        book_name: "Swami Vivekananda: A Biography",
        book_description: "Reading books is a kind of enjoyment. Reading books is a good habit. We bring you a different kinds of books. You can carry this book where ever you want. It is easy to carry. It can be an ideal gift to yourself and to your loved ones. Care instruction keep away from fire.",
        book_url: "https://m.media-amazon.com/images/I/8134Hol8MYL._SY425_.jpg",
        print_length: "164 pages",
        language: "English",
        author_name: "Swami Vivekananda",
        price: "194",
    },
    {
        id: 7,
        book_name: "Tales of Horror",
        book_description: "Prepare to immerse yourself into the heart of darkness as Nikesh Murali, Commonwealth Short Story Prize-winning author and creator of India’ s most critically acclaimed horror podcast Indian Noir weaves an unforgettable tapestry of bone-chilling scares and unrelenting terror. Whether you're a seasoned horror enthusiast or a newcomer to the genre, this anthology is sure to satisfy your cravings for all things terrifying.• By the host of the no. 1 podcast ‘ Indian Noir’ • A collection of unique and original horror stories• Features immersive world-building, creating a sense of place and atmosphere that can transport readers to a different time, place, or even dimension• Explores deeper themes, such as trauma, fear, and mortality• Generates a powerful emotional response in readers",
        book_url: "https://m.media-amazon.com/images/I/91+CQNeCtwL._SY425_.jpg",
        print_length: "272 pages",
        language: "English",
        author_name: "Nikesh Murali",
        price: "249",
    },
    {
        id: 8,
        book_name: "Rich Dad Poor Dad",
        book_description: "April of 2022 marks a 25-year milestone for the personal finance classic Rich Dad Poor Dad that still ranks as the #1 Personal Finance book of all time. And although 25 years have passed since Rich Dad Poor Dad was first published,readers will find that very little in the book itself has changed ― and for good reason. While so much in our world is changing a high speed, the lessons about money and the principles of Rich Dad Poor Dad haven’t changed. Today, as money continues to play a key role in our daily lives, the messages in Robert Kiyosaki’s international bestseller are more timely and more important than ever.",
        book_url: "https://m.media-amazon.com/images/I/81BE7eeKzAL._SY425_.jpg",
        print_length: "336 pages",
        language: "English",
        author_name: "Robert T. Kiyosaki",
        price: "389",
    },
    {
        id: 9,
        book_name: "The Subtle Art of Not Giving a F*ck",
        book_description: "In this generation-defining self-help guide, a superstar blogger cuts through the crap to show us how to stop trying to be “positive” all the time so that we can truly become better, happier people. For decades, we’ve been told that positive thinking is the key to a happy, rich life. “Fuck positivity,” Mark Manson says. “Let’s be honest, shit is fucked and we have to live with it.” In his wildly popular Internet blog, Manson doesn’t sugar-coat or equivocate. He tells it like it is—a dose of raw, refreshing, honest truth that is sorely lacking today. The Subtle Art of Not Giving a F**k is his antidote to the coddling, let’s-all-feel-good mind-set that has infected",
        book_url: "https://m.media-amazon.com/images/I/511vJPN7p5L._SX331_BO1,204,203,200_.jpg",
        print_length: "384 pages",
        language: "English",
        author_name: "Mark Manson",
        price: "272",
    },
    {
        id: 10,
        book_name: "Ikigai",
        book_description: "THE INTERNATIONAL BESTSELLER We all have an ikigai. It's the Japanese word for ‘a reason to live’ or ‘a reason to jump out of bed in the morning’. It’s the place where your needs, desires, ambitions, and satisfaction meet. A place of balance. Small wonder that finding your ikigai is closely linked to living longer. Finding your ikigai is easier than you might think. This book will help you work out what your own ikigai really is, and equip you to change your life. You have a purpose in this world: your skills, your interests, your desires and your history have made you the perfect candidate for something. All you have to do is find it. Do that, and you can make every single day of your life joyful and meaningful.",
        book_url: "https://m.media-amazon.com/images/I/51xwGSNX-EL._SX356_BO1,204,203,200_.jpg",
        print_length: "208 pages",
        language: "English",
        author_name: "Héctor García",
        price: "249",
    },
    {
        id: 11,
        book_name: "LINCHPIN",
        book_description: "In this compelling, accessible and purpose-filled book bestselling business author Seth Godin shows how you have the potential to make a big difference-and make yourself indispensable in the process-wherever you are.Why are some people easily outsourced, downsized, or freelanced into obscurity, while others have their pick of opportunities? In his most powerful book yet, Seth Godin argues that it's more essential than ever to become indispensable - to become a linchpin. Linchpins are the essential building blocks of great organizations: they invent, lead (regardless of title), connect others, make things happen, and create order out of chaos. They love their work and pour their best selves into it and turn each day into a kind of art - and, in today's world, they get the best jobs and the most freedom.Godin shows that the key to being indispensable is overcoming the fears that hold most of us back.",
        book_url: "https://m.media-amazon.com/images/I/51fGhgWMZKL._SX317_BO1,204,203,200_.jpg",
        print_length: "256 pages",
        language: "English",
        author_name: "Seth Godin",
        price: "294",
    },
    {
        id: 12,
        book_name: "Harry Potter and the Prisoner of Azkaban",
        book_description: "When the Knight Bus crashes through the darkness and screeches to a halt in front of him, it's the start of another far from ordinary year at Hogwarts for Harry Potter. Sirius Black, escaped mass-murderer and follower of Lord Voldemort, is on the run - and they say he is coming after Harry. In his first ever Divination class, Professor Trelawney sees an omen of death in Harry's tea leaves . But perhaps most terrifying of all are the Dementors patrolling the school grounds, with their soul-sucking kiss.",
        book_url: "https://m.media-amazon.com/images/I/51StPSSsneL._SX332_BO1,204,203,200_.jpg",
        print_length: "480 pages",
        language: "English",
        author_name: "J.K. Rowling",
        price: "305",
    },
    {
        id: 13,
        book_name: "Doglapan : The Hard Truth about Life and Start-Ups",
        book_description: "A young boy with a 'refugee' tag growing up in Delhi's Malviya Nagar outpaces his circumstances by becoming a rank-holder at the pinnacle of academic excellence in India-IIT Delhi. He goes on to do an MBA from the hallowed halls of IIM Ahmedabad, builds a career as an investment banker at Kotak Investment Banking and AmEx, and is pivotal in the making of two unicorns-Grofers, as CFO, and BharatPe, as co-founder.",
        book_url: "https://m.media-amazon.com/images/I/81InFh0R4UL._SY425_.jpg",
        print_length: "256 pages",
        language: "English",
        author_name: "Ashneer Grover",
        price: "311",
    },
    {
        id: 14,
        book_name: "Harry Potter and the Order of the Phoenix",
        book_description: "Dark times have come to Hogwarts. After the Dementors' attack on his cousin Dudley, Harry Potter knows that Voldemort will stop at nothing to find him. There are many who deny the Dark Lord's return, but Harry is not alone: a secret order gathers at Grimmauld Place to fight against the Dark forces. Harry must allow Professor Snape to teach him how to protect himself from Voldemort's savage assaults on his mind. But they are growing stronger by the day and Harry is running out of time.",
        book_url: "https://m.media-amazon.com/images/I/511+ftLvTUL._SX332_BO1,204,203,200_.jpg",
        print_length: "816 pages",
        language: "English",
        author_name: "J.K. Rowling",
        price: "475",
    },
    {
        id: 15,
        book_name: "REVOLUTION 2020",
        book_description: "Reading books is a kind of enjoyment. Reading books is a good habit. We bring you a different kinds of books. You can carry this book where ever you want. It is easy to carry. It can be an ideal gift to yourself and to your loved ones. Care instruction keep away from fire.",
        book_url: "https://m.media-amazon.com/images/I/817tkiYPPsL._SY425_.jpg",
        print_length: "296 pages",
        language: "English",
        author_name: "Chetan Bhagat",
        price: "360",
    },
    {
        id: 16,
        book_name: "11 Rules For Life",
        book_description: "Written in the inimitable style that has made Chetan one of India’s top-selling writers, this inspiring, easy-to-read and straight-talking guide will help you rewire your brain for success in today’s ultra-competitive and unfair world.",
        book_url: "https://m.media-amazon.com/images/I/41pyHp6YiGL._SY445_SX342_.jpg",
        print_length: "256 pages",
        language: "English",
        author_name: "Chetan Bhagat",
        price: "247",
    }
]